language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get clean
  - sudo apt-get update
  - pip install --upgrade pip
  - sudo apt-get install -qq python-numpy
  - sudo pip install opencv-python

script: make test
