language: python
python:
  - "2.7"
script: make test

compiler:
  - gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install python-dev python-numpy python-yaml

before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.8.2
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j8
  - sudo make install
  - cd ../../
#  - ln -s opencv/build/lib/cv2.so
