language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - sudo apt-get clean
  - sudo apt-get update
  - sudo apt-add-repository -y ppa:gijzelaar/opencv2.4
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy python-opencv

script: make test
