language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq libopencv-dev python-numpy python-opencv

script: make test
