---
# Preprocessing steps to perform on images before features are extracted.
preprocess:
    # Limit the maximum dimension for an input image (optional). The input
    # image is scaled down if width or height exceeds the value.
    maximum_dimension: 500

    # Perform segmentation on the image, where the background is removed.
    segmentation:
        # The number of segmentation iterations. Default is 5.
        iterations: 5
        # The margin of the region of interest from the edges of the image.
        # Default is 1.
        margin: 1
        # Where masked images are saved (optional).
        output_folder: images/masked/

# Features to be extracted from the images.
features:
    color_histograms: {BGR: 10, HSV: 10}
    #shape_outline: {resolution: 15}
    shape_360: {rotation: 0, step: 1, t: 8}
    #shape_360_color: {rotation: 0, step: 1, t: 8}

# Parameters for training the artificial neural network.
ann:
    # Number of hidden neuron layers. Default is 1
    hidden_layers: 1
    # Number of hidden neurons per hidden layer. Default is 8
    hidden_neurons: 8
    # Maximum number of epochs. Default is 500000
    epochs: 500000
    # Desired error. Default is 0.0001
    error: 0.0001
    # Learning rate. Default is 0.7
    learning_rate: 0.7
    # Connection rate. Default is 1, a fully connected network.
    connection_rate: 1

# List of class names used for classification. The order does not matter.
classes: [Brachypetalum, Cochlopetalum, Paphiopedilum, Parvisepalum]
