---
io:
    image_path: images/train/               # Top directory for image files. Images must be in level one sub directories.
    train_data: data/orchids_train.tsv      # Output file for training data.

preprocess:
    maximum_dimension: 500              # Limit the maximum dimension for an input image (optional). The input image is scaled down if width or height exceeds the value.

    segmentation:
        iterations: 5                   # The number of segmentation iterations. Default is 5.
        margin: 1                       # The margin of the region of interest from the edges of the image. Default is 1.
        output_folder: images/masked/   # Where masked images are saved (optional).

features:
    color_histograms: {BGR: 10, HSV: 10}
    #shape_outline: {resolution: 15}
    shape_360: {rotation: 0, step: 1, t: 8}
